version: '3.8'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/config/adminer.conf:/etc/nginx/adminer.conf 
      - ./nginx/config/grafana.conf:/etc/nginx/grafana.conf
      - ./nginx/config/nithub-management-system-app-1.conf:/etc/nginx/nithub-management-system-app-1.conf
      - ./nginx/config/nitmanager_cache.conf:/etc/nginx/nitmanager_cache.conf
      - ./nginx/config/nitmanager_db.conf:/etc/nginx/nitmanager_db.conf
      - ./nginx/config/nitprofile_database.conf:/etc/nginx/nitprofile_database.conf
      - ./nginx/config/nitprofile-backend-refactored-app-1.conf:/etc/nginx/nitprofile-backend-refactored-app-1.conf
      - ./nginx/config/prometheus.conf:/etc/nginx/prometheus.conf
      - ./nginx/log:/var/log/nginx
      - /etc/letsencrypt:/etc/letsencrypt:ro
      # add other config files (from config folder) here
    ports:
    - "80:80"
    - "443:443"

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
    ports:
      - 9090:9090

  grafana:
   image: grafana/grafana
   volumes:
      - grafana-storage:/var/lib/grafana
   ports:
     - 3300:3000
   environment:
      - GF_SECURITY_ADMIN_USER=nithub
      - GF_SECURITY_ADMIN_PASSWORD=nithub-password
   restart: always

  loki:
    image: grafana/loki
    volumes:
      - ./loki-config.yaml:/mnt/config/loki-config.yaml
    command: -config.file=/mnt/config/loki-config.yaml
    ports:
      - "3100:3100"

  promtail:
    image: grafana/promtail
    volumes:
      - ./promtail-config.yaml:/etc/promtail/config.yaml
      - /var/log:/var/log
      - /var/lib/docker/containers:/var/lib/docker/containers
      - /var/run/docker.sock:/var/run/docker.sock
    command: -config.file=/etc/promtail/config.yaml

networks:
  default:
    name: nithub
    external: false

volumes:
  grafana-storage: {}