global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
  
  - job_name: 'loki'
    scrape_interval: 5s
    static_configs:
      - targets: ['loki:3100']
  
  - job_name: 'apps'
    scrape_interval: 5s
    static_configs:
      - targets: ['nginx:80']